{{- if .Values.routing.enabled }}
{{- if .Values.routing.defaultMiddlewares }}
{{- if .Values.routing.defaultMiddlewares.headers }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: media-security-headers
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    {{- with .Values.routing.defaultMiddlewares.headers }}
    browserXssFilter: {{ .browserXssFilter | default true }}
    contentTypeNosniff: {{ .contentTypeNosniff | default true }}
    frameDeny: {{ .frameDeny | default false }}
    {{- if .customFrameOptionsValue }}
    customFrameOptionsValue: {{ .customFrameOptionsValue }}
    {{- end }}
    {{- if .stsSeconds }}
    stsSeconds: {{ .stsSeconds }}
    stsIncludeSubdomains: {{ .stsIncludeSubdomains | default true }}
    stsPreload: {{ .stsPreload | default true }}
    {{- end }}
    {{- end }}
{{- end }}

{{- if .Values.routing.defaultMiddlewares.rateLimit }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: media-rate-limit
  namespace: {{ .Release.Namespace }}
spec:
  rateLimit:
    average: {{ .Values.routing.defaultMiddlewares.rateLimit.average | default 100 }}
    burst: {{ .Values.routing.defaultMiddlewares.rateLimit.burst | default 50 }}
{{- end }}

{{- if .Values.routing.defaultMiddlewares.compress }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: media-compress
  namespace: {{ .Release.Namespace }}
spec:
  compress: {}
{{- end }}

{{- if .Values.routing.defaultMiddlewares.basicAuth }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: media-basic-auth
  namespace: {{ .Release.Namespace }}
spec:
  basicAuth:
    secret: {{ .Values.routing.defaultMiddlewares.basicAuth.secret }}
    {{- if .Values.routing.defaultMiddlewares.basicAuth.removeHeader }}
    removeHeader: true
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
