{{- if .Values.services.authentik.enabled }}
{{- if .Values.services.authentik.forwardAuth.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authentik-auth
  namespace: {{ .Release.Namespace }}
spec:
  forwardAuth:
    address: http://authentik.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.services.authentik.ports.http }}/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - X-authentik-username
      - X-authentik-groups
      - X-authentik-email
      - X-authentik-name
      - X-authentik-uid
      - X-authentik-jwt
      - X-authentik-meta-jwks
      - X-authentik-meta-outpost
      - X-authentik-meta-provider
      - X-authentik-meta-app
      - X-authentik-meta-version
{{- end }}
{{- end }}
