{{- if and .Values.services.authentik.enabled .Values.services.authentik.forwardAuth.enabled .Values.routing.enabled }}
{{- $routing := .Values.routing }}
---
# Catch-all route for Authentik outpost on the auth subdomain
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-outpost
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: authentik
spec:
  entryPoints:
    {{- range $routing.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - match: HostRegexp(`{subdomain:[a-z0-9-]+}.{{ $routing.domain }}`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      services:
        - name: authentik
          port: {{ .Values.services.authentik.ports.http }}
      priority: 15
  {{- if and $routing.tls.enabled (or $routing.tls.certResolver $routing.tls.secretName) }}
  tls:
    {{- if $routing.tls.certResolver }}
    certResolver: {{ $routing.tls.certResolver }}
    {{- end }}
    {{- if $routing.tls.secretName }}
    secretName: {{ $routing.tls.secretName }}
    {{- end }}
  {{- else if $routing.tls.enabled }}
  tls: {}
  {{- end }}
{{- end }}
