{{- if .Values.services.authentik.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: authentik-postgresql
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik-postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik-postgresql
    spec:
      {{- if .Values.services.authentik.postgresql.localConfig.enabled }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.services.authentik.postgresql.localConfig.node }}
      {{- end }}
      containers:
        - name: postgresql
          image: "{{ .Values.services.authentik.postgresql.image.repository }}:{{ .Values.services.authentik.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.services.authentik.postgresql.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.services.authentik.postgresql.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.services.authentik.postgresql.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-env
                  key: AUTHENTIK_POSTGRESQL__PASSWORD
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.services.authentik.postgresql.username | quote }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.services.authentik.postgresql.username | quote }}
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgresql-data
          {{- if and .Values.services.authentik.postgresql.localConfig .Values.services.authentik.postgresql.localConfig.enabled }}
          hostPath:
            path: {{ .Values.services.authentik.postgresql.localConfig.hostPath }}
            type: DirectoryOrCreate
          {{- else if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-data-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: authentik-postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: authentik-postgresql
{{- end }}
