{{- if .Values.services.authentik.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: authentik-redis
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.services.authentik.redis.image.repository }}:{{ .Values.services.authentik.redis.image.tag }}"
          imagePullPolicy: {{ .Values.services.authentik.redis.image.pullPolicy }}
          command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: redis-data
              mountPath: /data
              subPath: authentik-redis
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: redis-data
          {{- if .Values.storage.nfs.enabled }}
          persistentVolumeClaim:
            claimName: media-data-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: authentik-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: authentik-redis
{{- end }}
