{{- if .Values.services.authentik.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: authentik-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: {{ .Values.services.authentik.secretKey | quote }}
  AUTHENTIK_POSTGRESQL__HOST: "authentik-postgresql"
  AUTHENTIK_POSTGRESQL__PORT: "5432"
  AUTHENTIK_POSTGRESQL__NAME: {{ .Values.services.authentik.postgresql.database | quote }}
  AUTHENTIK_POSTGRESQL__USER: {{ .Values.services.authentik.postgresql.username | quote }}
  AUTHENTIK_POSTGRESQL__PASSWORD: {{ .Values.services.authentik.postgresql.password | quote }}
  AUTHENTIK_REDIS__HOST: "authentik-redis"
  AUTHENTIK_REDIS__PORT: "6379"
  {{- if .Values.services.authentik.email.enabled }}
  AUTHENTIK_EMAIL__HOST: {{ .Values.services.authentik.email.host | quote }}
  AUTHENTIK_EMAIL__PORT: {{ .Values.services.authentik.email.port | quote }}
  AUTHENTIK_EMAIL__USERNAME: {{ .Values.services.authentik.email.username | quote }}
  AUTHENTIK_EMAIL__PASSWORD: {{ .Values.services.authentik.email.password | quote }}
  AUTHENTIK_EMAIL__USE_TLS: {{ .Values.services.authentik.email.useTLS | quote }}
  AUTHENTIK_EMAIL__FROM: {{ .Values.services.authentik.email.from | quote }}
  {{- end }}
{{- end }}
